### ISSUE TITLE
aix_chdev[inet0] chdev device inet0 has not attribute route

### ISSUE THREAD

**Issue by gagipro** [chef-cookbooks/aix#105]
### Cookbook version
2.2

### Chef-client version
13.6.4

### Platform Details
7100-04-03-1642

### Scenario:
trying to add a route for a specific network

### Steps to Reproduce:
aix_chdev "inet0" do
  attributes("route" => "net,-hopcount,1,-netmask,#{dest_mask},#{dest_subnet},#{gateway}")
  notifies :update, 'aix_chdev[inet0]', :immediately
  action :nothing
  action :update
end

### Expected Result:
lsattr -El inet0
should contain new route.

got to do it with embedded shell loosing AIX cookbook benefits.

### Actual Result:
RuntimeError
    ------------
    chdev device inet0 has not attribute route

**Comment by gagipro** [comment]
This seems to work :+1: 
 
aix_chdev "inet0" do
  attributes(
      route: "net,-hopcount,1,-netmask,#{dest_mask},#{dest_subnet},#{gateway}"
  )
#  notifies :update, 'aix_chdev[inet0]', :immediately
  action :nothing
  action :update
end

**Comment by trickyearlobe** [comment]
Its happening because the resource expects attributes to be specified as symbols rather than strings. My PR #94 does an automatic conversion of strings to symbols.
