### ISSUE TITLE
Support for reboot and continue for chef?

### ISSUE THREAD

**Issue by jkohlmeier** [chef-cookbooks/aix#27]
Hey team.

Ive used this cookbook as my dependency for my oracle cookbooks.  Would love if 'reboot' would work somewhat better. If i use the reboot command. It hangs and i have to ctrl-C to get out, then manually wait for the LPAR to come back up before I restart. Has anyone found a good way to handle rebooting on AIX?

**Comment by christopherousseau** [comment]
Hi Jkohlmeier and welcome onboard ! :)

The right way to reboot an AIX box is 'shutdown -Fr' , actually. Did you try it ?

**Comment by jkohlmeier** [comment]
Requires that you ctrl-c out of chef workstation. THen you have to 
manually wait for the AIX system to come back. Then you have to restart 
the bootstrap. Ok. fine. but doesnt chef support reboot with continuation 
on other platforms? I am assuming that, that is the correct usage of 
reboot? Or does eveyone have to restart their chef bootstrap after a 
reboot.

I use only bootstrap command for provisioning. Perhaps i should be using 
chef differently...?

Anyway. I know this isnt the right place. but the AIX minds are on this 
cookbook. If anyone has a good means, or metaphor for using chef with AIX, 
i'd love feedback.

So my usage is:
a) use aix cookbook. make change to the AIX kernel.
b) use the reboot command to restart the OS (it does do the shutdown -Fr). 

c) ctrl-c out of chef bootstrap workstation, as it will hang forever.
d) manually look to see when the aix lpar is back up.
e) then restart my oracle cookbook to continue the installation.

Otherwise, i love chef. and aix cookcook i heavily lean on.



Jubal Kohlmeier             jubal@us.ibm.com
503-747-1333                 503-502-7733 cell
IT Specialist  Oracle Applications Benchmark

**Comment by chmod666org** [comment]
Hi Jkohlmeier, in a general way I'm not sure this is a good idea to reboot a machine using a chef recipe.
If you can explain by an example what you really want to do I can help you.
IMHO I think the reboot is the last thing you need to do in a recipe if it is really mandatory for you to reboot.
I haven't yet work on a provider doing such a thing but I'm almost sure that if there is one it is not AIX aware. If you want we  can try to work together to make it work in your environment. (I'm actually coding a lot or LWRP and HWRP for AIX).
I think we have to modify this rebooter.rb and add a special case for AIX, but by looking at the code I assume it is already working for AIX : https://github.com/chef/chef/blob/c1a389c2a8452e9b796aa1d34c4d9e51f4af30c7/lib/chef/platform/rebooter.rb
Have you tried using the reboot official resource : https://docs.chef.io/resource_reboot.html (use the reboot resource in your recipe instead of a execute resource).
I'll try tomorrow and let you know.
Regards,
B.

**Comment by jkohlmeier** [comment]
Its very simple. Most kernel changes require a reboot to become effective 
in AIX. In oracle database cookbook. i have to enable the IOCP device, 
which requires a reboot for the dbms server to continue installation. In 
Oracle EBS cookbook, I require changes to ncargs, and maxuproc. maxuproc 
(total number of proccesses in the system) require a reboot. Some 
tunables, which you now support require reboot to become effective. 
There's no alternative. rebooting is required. 

The rebooter.rb i assume is the resource reboot command that is documented 
in CHEF? It says its not supported in but a few OS's.  I am using the 
reboot source. Here is my current code.
To me the work-around is ugly. However. unless chef supported rebooting of 
AIX and re-starting, I don't see any other way for first-time provisioning 
my oracle cookbooks.

Jubal

---------------------------------------------------------------------------------------
unless File.file?( "#{reboot_completed}" )
  execute "kernel_rebooting_#{node[:hostname]}" do
    user 'root'
    group node[:root_group]
    command "touch #{reboot_completed}"
    creates       "#{reboot_completed}"
  end

  reboot 'Node_#{node[:hostname]}_requires_reboot' do
    action :reboot_now
    reason "Kernel Changes require rebooting. \r\nChef will not come 
back.\n"\
      "YOU MUST EXIT CHEF(hit ctrl-c), as it WONT come back on its 
own.\n"\
      "Then WAIT for the NODE to be up, before you restart the Install."
  end
end
-----------------------------------------


Jubal Kohlmeier             jubal@us.ibm.com
503-747-1333                 503-502-7733 cell
IT Specialist  Oracle Applications Benchmark

**Comment by chmod666org** [comment]
Jubal,
If the pain point is located on the iocp problem which is required to continue the installation a reboot is not required. You can just use the "mkdev -l iocp0" command . Then use the chdev resource of this cookbook to put the autoconfig attribute to "available". ncargs and maxuproc can also be changed using the chdev resource but I think these ones are not necessary to continue you installation. Then at the end reboot.
Do you agree ?

**Comment by chmod666org** [comment]
Closing. No answer.

**Comment by aamircse09** [comment]
I have done it using FLAG file method, example given below. Tested on Windows server.
Recommendations: Use DATA_BAGS for Domain name, Username, Password

Example of domain join-

> ---------------------------Script Start------------------------
>     
>         powershell_script 'Domain_Join' do
>         guard_interpreter :powershell_script
>         code -domainJoin
>         $currentTime = Get-Date
>         $currentTimeString = $currentTime.ToString()
>         
>       $systemDomain = (Get-WmiObject Win32_ComputerSystem).Domain
>       If (($systemDomain) -eq 'domainName')
>       { 
>         Try {
>       write-host "$env:computerName is DOMAIN MEMBER"
>       Remove-Item C:\\DomainJoinFlag.txt -ErrorAction Stop
>       Unregister-ScheduledTask -TaskName "Chef client schedule_DJ" -Confirm:$false
>       } # end of Try
>               Catch [System.Management.Automation.ItemNotFoundException]
>                 { write-host "Server is already domain member, Or Exception raised due to either missing FLAG file or Server startup schedule task configuration." 
>                   eventcreate /t INFORMATION /ID 0909 /L APPLICATION /SO "ChefClient_$env:computerName" /D "Server is already domain member, Or Exception raised due to either missing FLAG file or Server startup schedule task configuration. Refer to the CHEF reciepie for DomainJoin or check Administrative credentials for creting schedule task"}
>                 }
>         else { write-host "$env:computerName is NOT domain member, joining the server to the domain. Server will be rebooting in a while..."
>                 eventcreate /t INFORMATION /ID 0909 /L APPLICATION /SO "ChefClient_$env:computerName" /D "Joining the server : $env:ComputerName to the domain ININLAB.COM (Server Time): $currentTimeString"
>                 New-Item C:\\DomainJoinFlag.txt -type file -force
>                 write-host "$env:computerName DOMAIN JOIN INITIATED for the server"
>                 $cred = New-Object System.Management.Automation.PsCredential("domain\\domain_user", (ConvertTo-SecureString "Password" -AsPlainText -Force))
>                 Add-Computer -DomainName "domainName" -Credential $cred -OUPath "OU=HyperV,OU=Infrastructure,OU=Servers,DC=domain,DC=name"
>                 shutdown -r -t 120
>                 } #end_of_else
>                 domainJoin
>       notifies :run, 'windows_task[Chef client schedule_DJ]', :immediately
>     end
>     
>     windows_task 'Chef client schedule_DJ' do
>       user 'SYSTEM'
>       command 'chef-client -L C:\chef\chef-client_after_reboot_domainJoin.log'
>       run_level :highest
>       frequency :onstart
>       frequency_modifier 30
>       action :create
>       only_if { ::File.exist?('C:\\DomainJoinFlag.txt') }
>     end
>     
>---------------------------Script Ends------------------------
