### ISSUE TITLE
chsec resource bugs

### ISSUE THREAD

**Issue by aklyachkin** [chef-cookbooks/aix#31]
1. aix/providers/chsec.rb

load_current_resource, line 79:
```ruby
# if we found the stanza, and we match another stanza found_stanza=0
found_stanza = false if found_stanza && line =~ /\w:/
```
The both lines must be higher, after line 66, before filling hash table. Otherwise, if you try to change some section, other then "usw" ;-) the following error can appear:

    ================================================================================
    Error executing action `update` on resource 'aix_chsec[/etc/security/login.cfg]'
    ================================================================================
    
    NoMethodError
    -------------
    undefined method `chomp' for nil:NilClass

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/aix/providers/chsec.rb:74:in `block in load_current_resource'
    /var/chef/cache/cookbooks/aix/providers/chsec.rb:61:in `each_line'
    /var/chef/cache/cookbooks/aix/providers/chsec.rb:61:in `load_current_resource'

2. aix/providers/chsec.rb

update, line 102:

```ruby
chsec_s = chsec_s << " -a #{key}=#{@new_resource.attributes[key]}"
```
Please not the quotes:

    $ chsec
    Usage: chsec -f file -s stanza -a "attr=value" ...

The line must be:

```ruby
chsec_s = chsec_s << " -a \"#{key}=#{@new_resource.attributes[key]}\""
```

**Comment by chmod666org** [comment]
Will update this tonight.

**Comment by chmod666org** [comment]
Updated, test in my environment. Working ok now.
Thanks
