### ISSUE TITLE
no : problem with first tunable of the list when action is :update

### ISSUE THREAD

**Issue by christopherousseau** [chef-cookbooks/aix#32]
hey, I have this recipe : 
`aix_no "settings network securiy recommandations" do
  tunables(:udp_pmtu_discover => 0, :tcp_pmtu_discover => 0, :icmpaddressmask => 0, :directed_broadcast => 0, :bcastping => 0, :ipforwarding => 0, :ipsendred
irects => 0, :ipsrcrouteforward => 0, :ipsrcroutesend => 0, :ip6srcrouteforward =>0, :ipignoreredirects => 1, :arpt_killc => 1, :clean_partial_conns => 1, :t
cp_nodelayack => 1, :tcp_recvspace => 262144, :tcp_sendspace => 262144, :tcp_tcpsecure => 7, :sb_max => 1048576)
  set_default
  action :update
end
`
And when I run it, I've got this error : 
`    ================================================================================
    Error executing action `update` on resource 'aix_no[settings network securiy recommandations]'
    ================================================================================

    RuntimeError
    ------------
    no: udp_pmtu_discover does not exist

`

But this tunable exists (checked with no -x), so I'm wondering if it is a bug, or if I mistyped something...

**Comment by chmod666org** [comment]
will check this. Will let you know asap.

**Comment by chmod666org** [comment]
Works ok for me
It seems that your set_default is not set to true please put set_default maybe it's the problem. There are some spaces in your example (:ipsendred irects).
My output:
[..]
Setting udp_pmtu_discover to 0
    - no: setting tunable udp_pmtu_discover=0Setting tcp_pmtu_discover to 0
Setting tcp_pmtu_discover to 0 in nextboot file

    - no: setting tunable tcp_pmtu_discover=0

Running handlers:
Running handlers complete
[..]

Tell me if issue can be close.

If not give me the exact AIX version and no -x output please.
