### ISSUE TITLE
VG commands in this cookbook?

### ISSUE THREAD

**Issue by alanwthatcher** [chef-cookbooks/aix#33]
I am developing an LVM cookbook for AIX, wondering if it would be good to add to this cookbook, or should it be a separate cookbook?  I mimicked the structure of the resources in this cookbook.

So far I have mkvg and chvg in the LWRP called 'volume group'.  So if it is in this cookbook, i guess it would be referenced as a resource 'aix_volume_group'.  I'm newish to this, so looking for adivice.

If it would be welcome in this cookbook, i can make PR for it soon.  If it should be included in a new cookbook (or if i missed one already out there), I can do that.

**Comment by chmod666org** [comment]
Hi Alan,
Every new thing is welcome here. But regarding lvm in my personnal opinion the best way to do that is to use the existing chef lvm cookbook and adapt it on AIX https://github.com/chef-cookbooks/lvm. By doing this we will have a cookbook managing lv/pv/vg.
As far as I know IBM is working on it (are you from IBM ?). Can you please share/tell me more about your code and about this LWRP (attributes, actions and so on). We will then take a decision about this !
Regards,
B.

**Comment by alanwthatcher** [comment]
I am not from IBM.  I am just a user, and got tired of putting the commands as execute resources.  IBM working on it could be interpreted in different ways :)

I thought about the current LVM cookbook.  I didn't go that way for a couple of reasons primarily related to my newness to the product for now:

1. I wasn't exactly sure how to go about makging it AIX compliant with the way it was structured
2. I didn't know if it could be used without the requirement for the gems, which are not useful for AIX afaik

As for my code I just essentially obfuscated the mkvg and chvg commands for now.  Do you want some snippets, or?

**Comment by alanwthatcher** [comment]
One of the main things that spurred me on, is that I didn't like having to specify the PV to use in the execute resources I was creating, or building logic for the recipe to determine the specific one(s) to use.

So I built into my LVM cookbook the ability to chose disk(s) specifically by name, by a "best fit" algorithm for a single disk fitting a certain GB requirement, or through an all option to use all available disks.

For the options for both mkvg and chvg, I created an command line option to attribute map so they can be referenced by more chef-like terminology in the recipes.  I also left it open for user specified options to be placed in.

**Comment by chmod666org** [comment]
I know that internal dev in Austin are working on the lvm cookbook for AIX.
What you can do is make a PR and I'll review it as soon as possible and make my comments (please run foodcritic and rubocop before PR if possible ;-) ).
... and thanks a lot for your job it is much appreciated !

**Comment by chmod666org** [comment]
Awesome ! I was doing the exact same thing for alt_disk_copy (choosing the disk by name, size, exact same size, bigger size, and so on ...)

**Comment by alanwthatcher** [comment]
I didn't have the options of exact or bigger size so far for disk selection.  I settled with a algorithm that essentially selects all disks of at least the size requested,then chooses the smallest of those.  If there are multiples of equal size in the "smallest adequately sized disks", it just chooses the first one.

I have not run foodcritic or rubocop :) but will attempt it!

**Comment by chmod666org** [comment]
Great !
Let me know. Waiting for your PR.

**Comment by alanwthatcher** [comment]
rubocop is mean lol, working on it

**Comment by alanwthatcher** [comment]
submitted a PR for review of code.

**Comment by tas50** [comment]
Looks like this change was released a while back. I'm going to close this out now
