### ISSUE TITLE
Rescue the installation of the wpar gem

### ISSUE THREAD

**Issue by tas50** [chef-cookbooks/aix#51]
We can make this seamlessly install and we should.

**Comment by adejoux** [comment]
Hello,

I would like to have a example of how to integrate properly this gem. Could you point me on a good example ? And I will fix my code cleanly.

Thanks,

Alain

**Comment by jkohlmeier** [comment]
i would also. i would like to update my cookbook oracle_ebs to use the latest aix 1.1.0,

**Comment by tas50** [comment]
The LVM cookbook is a good example of how to do this

**Comment by jkohlmeier** [comment]
looked at lvm for finding how to download wpars gem.  it suggests these actions:
+ gem search wpar --both

*** LOCAL GEMS ***
*** REMOTE GEMS ***

aix-wpar (0.1.0)
facwparser (0.0.9)
kitchen-wpar (0.1.0)
wparp (0.0.6)
wparser (0.1.3)

so installed aix-wpar 0.1.0 using:
gem install aix-wpar

was successful installing. but still the aix 1.1.0 cannot find 'wpars'.   IS aix-wpar should be the name of the gem?

**Comment by adejoux** [comment]
Hello,

yes. The gem is aix-wpar.

I am trying to update the cookbook to make it work properly like the di-ruby-lvm gem in lvm cookbook. Currently aix-wpar is in the Gemfile of the cookbook. My understanding is I should remove it and create a dedicated library to manage the gem installation itself. 

Regards,

Alain

**Comment by tas50** [comment]
This is fixed in the 1.2 release
