### ISSUE TITLE
First try to create a logical volume on rootvg : error

### ISSUE THREAD

**Issue by christopherousseau** [chef-cookbooks/aix#53]
### Cookbook version

1.1.0
### Chef-client version

12.14.77
### Platform Details

AIX 7.2
### Scenario:

Testing LVM support with first try to create a LV on rootvg (which does exist, obviously)
### Steps to Reproduce:

recipe content : 

aix_logical_volume 'lvtest' do
  group 'rootvg'
  size   512
  copies 1
  action :create
end
### Expected Result:

lvtest created on rootvg
### Actual Result:

I get this : 
- aix_logical_volume[lvtest] action create[2016-09-26T10:28:59+02:00] FATAL: volume group "rootvg" does not exist!
  (up to date)

Am I doing something wrong is there a small bug in the aix/librairies/lvmobj_lv.rb ?

**Comment by christopherousseau** [comment]
same behaviour with creating a FS : 
  * aix_filesystem[/test] action create[2016-09-26T13:43:12+02:00] FATAL: logical volume "test" does not exist!

Got the same error wether the LV has been previously created or not. 

I gotta add that on this server I only have one VG (rootvg), if it is of any help.

**Comment by r3n1k** [comment]
Same issue here on AIX 6.1, cookbook 1.2.0 , either for creating a VG, a LV, or a FS on rootvg/datavg
Unusable as it is :/

**Comment by r3n1k** [comment]
It works fine with the original aixlvm version at https://github.com/aix-chef/aixlvm.
So I guess something was broken during merge or refactor.

**Comment by chmod666org** [comment]
I confirm it's working with the original one. 
Confirm that code was refactored maybe rubocoped or any linter.
Trying to figure out what's the difference

**Comment by atos-hurstel** [comment]
Looks like you said:
Line 38 in libraries/tools.rb:
`return stdout.slice!(0..-(1 + $/.size))`
has been misreplaced by 
`return stdout.slice!(0..-(1 + $INPUT_RECORD_SEPARATOR.size))`

**Comment by chmod666org** [comment]
yep my PR replacing by $\ is complaining with rubocop .
" Prefer $INPUT_RECORD_SEPARATOR or $RS from the stdlib 'English' module over $/."
I'm making some tests to check what's the best solution

**Comment by chmod666org** [comment]
ok we just need to add require 'English' at top of tools.rb

**Comment by chmod666org** [comment]
Issue is solved by this commit https://github.com/chef-cookbooks/aix/commit/4cf227ff26f8c2a5741c75cbe462a354e38cd5a3
Thanks to @atos-hurstel for finding the bug.

**Comment by chmod666org** [comment]
Issue is solved by this commit 4cf227f
