### ISSUE TITLE
xpm package is duplicated in library/helpers.rb

### ISSUE THREAD

**Issue by thorhs** [chef-cookbooks/aix#74]
### Cookbook version
1.0.1 (also present in master)

### Chef-client version
12.14.89

### Platform Details
7100-04-01-1543

### Scenario:
Run chef-client which includes the aix cookbook

### Steps to Reproduce:
Run chef-client which includes the aix cookbook

### Expected Result:
When running the chef-client, we should not be seeing warnings related to duplicate keys.

### Actual Result:
/var/chef/cache/cookbooks/aix/libraries/helpers.rb:345: warning: key "xpm" is duplicated and overwritten on line 346

I'm fairly new to Ruby, but it seems to me that the 5.2 version of the xpm package is being overwritten by the 6.1 version:

          'xpm' => { version: '3.4k-8', rpm: 'xpm/xpm-3.4k-8.aix5.2.ppc.rpm' },
          'xpm' => { version: '3.4k-8', rpm: 'xpm/xpm-3.4k-8.aix6.1.ppc.rpm' },

I can submit a PR to resolve this, I assume the 6.1 version should be the one that remains?  Should this be handled differently, like keeping both versions under different names?

**Comment by tas50** [comment]
Thanks for the fix
