### ISSUE TITLE
Implement WPAR management LWRP

### ISSUE THREAD

**Issue by juliandunn** [chef-cookbooks/aix#9]
Could be cool to have a basic WPAR management LWRP.

**Comment by adejoux** [comment]
I have a customer requesting it. I started to work on implementing it. I need to have it production ready for June :)

**Comment by juliandunn** [comment]
That's cool :grin: thanks @adejoux looking forward to your PR!

**Comment by chmod666org** [comment]
wpar LWRP coded by @adejoux
